name: BuildAndPublish
on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*
  pull_request: 

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      elasticsearch:
        image: mongo
        ports:
          - 27017:27017
        options: -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=123456

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet 3
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: build and publish
        shell: pwsh
        env:
          MONGODB_TEST_CONNECTION_STRING: 'mongodb://admin:123456@localhost:27017'
        run: |
          ./build.ps1 -nugetPublish $true -nugetApiKey ${{ secrets.NUGET_API_KEY }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'artifacts/NuGet'
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuget-packages
          path: artifacts/NuGet
